# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170707_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'verbose_name': 'Book Copy', 'verbose_name_plural': 'Book Copies'},
        ),
    ]
